# SuperNETs Links / Foenum
except ban {
	mask *@127.0.0.1;
	type { kline; gline; zline; gzline; shun; blacklist; }
}

# IRCCloud
except ban { 
	mask *@5.254.36.56/29;
	mask *@5.254.36.104/29;
	mask *@2a03:5180:f::/62;
	mask *@2a03:5180:f:4::/63;
	mask *@2a03:5180:f:6::/64;
	type { kline; gline; zline; gzline; shun; blacklist; }
}

# KiwiIRC
except ban { 
	mask *@107.161.19.53;
	mask *@107.161.19.109;
	mask *@109.169.31.4;
	mask *@109.169.31.13; # KiwiIRC Verify Bot (out.kiwiirc.com)
	type { kline; gline; zline; gzline; shun; blacklist; }
}

# Mibbit
except ban {
	mask *@207.192.75.252;                 # ircip1.mibbit.com
	mask *@64.62.228.82;                   # ircip2.mibbit.com
	mask *@78.129.202.38;                  # ircip3.mibbit.com
	mask *@109.169.29.95;                  # ircip4.mibbit.com
	mask *@97.107.138.109;                 # bot.search.mibbit.com
	mask *@2600:3c03::f03c:91ff:fe96:c1fa; # bot.search.mibbit.com
	type { kline; gline; zline; gzline; shun; blacklist; }
}

# Scanners
except ban {
	mask *@85.25.10.40;  # anaconda.netsplit.de
	mask *@149.56.47.33; # stats-grabber.ircdocs.horse
	type { kline; gline; zline; gzline; shun; blacklist; }
}