# IRCCloud
except ban { mask *@192.184.9.108;      } # highgate.irccloud.com
except ban { mask *@192.184.9.110;      } # ealing.irccloud.com
except ban { mask *@192.184.9.112;      } # charlton.irccloud.com
except ban { mask *@192.184.10.118;     } # brockwell.irccloud.com
except ban { mask *@192.184.10.9;       } # tooting.irccloud.com
except ban { mask *@192.184.8.73;       } # hathersage.irccloud.com
except ban { mask *@192.184.8.103;      } # stonehaven.irccloud.com
except ban { mask *@5.254.36.57;        } # tinside.irccloud.com
except ban { mask *@5.254.36.56/29;     } # IPv4
except ban { mask *@2001:67c:2f08::/48; } # IPv6
except ban { mask *@2a03:5180:f::/64;   } # IPv6

# IRC Source
except ban { mask *@49.56.142.157;            } # yin.ircs.me
except ban { mask *@149.56.142.163;           } # yang.ircs.me
except ban { mask *@2607:5300:201:3100::13dd; } # yin.ircs.me
except ban { mask *@2607:5300:201:3100::299d; } # yang.ircs.me

# KiwiIRC
except ban { mask *@107.161.19.53;  }
except ban { mask *@107.161.19.109; }
except ban { mask *@109.169.31.4;   }
except ban { mask *@109.169.31.13;  } # KiwiIRC Verify Bot (out.kiwiirc.com)

# Mibbit
except ban { mask *@207.192.75.252;                 } # ircip1.mibbit.com
except ban { mask *@64.62.228.82;                   } # ircip2.mibbit.com
except ban { mask *@78.129.202.38;                  } # ircip3.mibbit.com
except ban { mask *@109.169.29.95;                  } # ircip4.mibbit.com
except ban { mask *@97.107.138.109;                 } # bot.search.mibbit.com
except ban { mask *@2600:3c03::f03c:91ff:fe96:c1fa; } # bot.search.mibbit.com

# Netsplit
except ban { mask *@85.25.137.63; } # eagle.netsplit.de
except ban { mask *@85.25.10.40;  } # anaconda.netsplit.de