include "links.conf";
include "modules.conf";

admin { "" }

me { name "irc.supernets.org"; info "SuperNETs IRC Network"; sid 001; }

class opers   { pingfreq 120; maxclients  2; sendq 1M; options { nofakelag; } }
class servers { pingfreq 120; maxclients 10; sendq 1M; connfreq 30;           }

allow { ip 127.0.0.1; class opers; maxperip 2; }

listen { ip 127.0.0.1; port REDACTED; options { clientsonly; tls; } } # Admin
listen { ip *;         port REDACTED; options { serversonly; tls; } } # Links
listen { ip 127.0.0.1; port REDACTED; options { serversonly;      } } # Anope

link services.supernets.org {
	incoming { mask 127.0.0.1; port REDACTED; }
	password "REDACTED";
	class servers;
}

log "ircd.log" { flags { errors; } maxsize 1K; }

except ban { mask *@127.0.0.1; }

ulines { services.supernets.org; }

set {
	gline-address "banned@supernets.org";
	kline-address "banned@supernets.org";
	modes-on-connect "+ipTx";
	modes-on-oper "+HIq";
	snomask-on-oper "+bcFfkGsSo"
	modes-on-join "+ns";
	level-on-join "op";
	static-quit "EMO-QUIT";
	static-part "EMO-PART";
	nick-length 20;
	network-name "SuperNETs";
	default-server "irc.supernets.org";
	services-server "services.supernets.org";
	sasl-server "services.supernets.org";
	help-channel "#help";
	channel-command-prefix "`!@$.";
	cloak-method ip;
	cloak-keys {
		"REDACTED";
		"REDACTED";
		"REDACTED";
	}
	hiddenhost-prefix "SUPER";
	default-bantime 1d;
	manual-ban-target ip;
}