include "links.conf";
include "modules.conf";

admin { ""; }

me { name "irc.supernets.org"; info "SuperNETs IRC Network"; sid 001; }

class servers { pingfreq 120; maxclients 10; sendq 1M; connfreq 30; }

listen { ip *;         port REDACTED; options { serversonly; tls; } } # Links
listen { ip 127.0.0.1; port REDACTED; options { serversonly;      } } # Anope

link services.supernets.org {
	incoming { mask 127.0.0.1; port REDACTED; }
	password "REDACTED";
	class servers;
}

log "ircd.log" { flags { errors; } maxsize 1K; }

except ban { mask *@127.0.0.1; }

ulines { services.supernets.org; }

set {
	gline-address "banned@supernets.org";
	kline-address "banned@supernets.org";
	network-name "SuperNETs";
	default-server "irc.supernets.org";
	services-server "services.supernets.org";
	sasl-server "services.supernets.org";
	help-channel "#help";
	cloak-method ip;
	cloak-keys {
		"REDACTED";
		"REDACTED";
		"REDACTED";
	}
}