include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/badwords.conf";
include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/except.conf";
include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/ircd.conf";
include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/modules.conf";
include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/opers.conf";
include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/snomasks.conf";
include "https://USERNAME:PASSWORD@hub.supernets.org:PORT/spamfilter.conf";

me { name "example.supernets.org"; info "SuperNETS IRC Network"; sid XXX; }

listen {
	ip *;
	port 6697;
	options { clientsonly; tls; }
	tls-options {
		certificate "tls/irc.crt";
		key         "tls/irc.key";
	}
}
listen {
	ip *;
	port 9000;
	options { clientsonly; tls; }
	tls-options {
		certificate "tls/irc.crt";
		key         "tls/irc.key";
	}
}

listen {        
	file "/etc/tor/unrealircd/tor_ircd.socket";
	mode 0777;
	spoof-ip 127.0.0.2;
}
listen {
	file "/etc/tor/unrealircd/tor_tls_ircd.socket";
	mode 0777;
	spoof-ip 127.0.0.2;
	options { tls; }
}
