include "https://USERNAME:PASSWORD@HOSTNAME:PORT/badwords.conf";
include "https://USERNAME:PASSWORD@HOSTNAME:PORT/except.conf";
include "https://USERNAME:PASSWORD@HOSTNAME:PORT/ircd.conf";
include "https://USERNAME:PASSWORD@HOSTNAME:PORT/modules.conf";
include "https://USERNAME:PASSWORD@HOSTNAME:PORT/opers.conf";
include "https://USERNAME:PASSWORD@HOSTNAME:PORT/snomasks.conf";
include "https://USERNAME:PASSWORD@HOSTNAME:PORT/spamfilter.conf";
me { name "example.supernets.org"; info "SuperNETS IRC Network"; sid XXX; }
listen {
	ip *;
	port 6697;
	options { clientsonly; tls; }
	tls-options {
		certificate "tls/irc.crt";
		key         "tls/irc.key";
	}
}
listen {
	ip *;
	port 9000;
	options { clientsonly; tls; }
	tls-options {
		certificate "tls/irc.crt";
		key         "tls/irc.key";
	}
}