[all:vars]
ansible_user=root
ansible_ssh_private_key_file=supernets.private # Assumed to be in the same directory as the inventory file

[ircd_servers]
# Add your servers below in the format:
# hostname ansible_host=ip_address ansible_port=ssh_port leaf_name=server_leaf_name
# Examples:
# ircd01 ansible_host=192.168.1.10 ansible_port=22    leaf_name=us-east
# ircd02 ansible_host=192.168.1.11 ansible_port=2222  leaf_name=eu-west
# ircd03 ansible_host=192.168.1.12 ansible_port=42022 leaf_name=asia-east 